environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37

build: off

install:
  - pip install tox
    # We need this to propagate the Python path for fixtures in test_srt_tools
  - "PATH > %TEMP%\\path"

test_script:
  - tox
